travis:
  secure:
    BINSTAR_TOKEN: Z+WdVtCrrkUsYKpP6jeV+t6WhthgCGU76/Hg5OrVIDm2VBQbmJMdaK5ba8AE3VaHCjBjcc9V+ppjrxdvS2fX6MoQ3LTDEA3hIoRu13LTD9ABnLKMXPKoDwMvfA6OEFHE/VdFMrxcC09G2xlEyr6qf9oK77mewfnQLKLpv76NH6aFq8okHojMWn74+r7OnWYMJctLJt2JSM+bCu0AtDSGn/Z1kmW03i3n/C54wzEAo+FYnyMA+lrfWiXipHzxuBODh4ktksDt5otr5+eMOtXmZTGEkfn4YFRbxLQ/9q10X9w+czb7FxWZ/2dnBBLuYI5iifvtglMBNXBmq9FMqyRBDN4kbR+AoParXfDhAe39K802+NG3VP5sVw8ttBsp3QnvRzJo/5s/zxfTgi8XXUBL8W27SfRUWCdXDE/jgJl8N6FedyOmq89/uDpLEki9VB6BB+K5P3soOiwQg2uwUtXuhnAoqydtLe00AJKOgBgAKlZgeTdZcRTAx7rYuq9pl14igDouqhRUkDmrDrHTcHcgt3aLVgkWARZA2qoaniKa02qtk10BLxD25d5OMw/hz7/MmwhdPsXVmbxa0i1lONmVzKkl4jAEOjIelfY0TudapWnTHQ8YVfPPrxHddWUB6syw63OlUlr6+GQUCUBjosx3FYGRTPS1SC5tqZyWeGfdw3E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
