travis:
  secure:
    BINSTAR_TOKEN: xIBjGVdsZFqjSdfQcnJFFcSkQywX/hqf1bIdFQXrBQYWW1vxxafNcCwrLPdYLy+LcWO2p6D0e8LeIiEikvV1snlcEJcbC9zFcNlS8LtDGpUErPoH6LtfDCPT4eFJGmi9n69Y+N2dIVCDatyKJgsScwcIQCBbGH/EfNroLJ/v4lF1b3JPBU1F9uUj1JnxeMwzCbQbxsEwrdJw1WWwZEMol63EyfXY4iiTrmixfDPVgQGpAl6BBH8VanNP050t5pXV5/Xr8w5mc/XnikY058B0aW5Eb2v7cNq5hryOGFI/e9KSzs8wclQp42GAyEZ9r7QzgCPdP4INA49hsD7mobaeWoY5ntEYnm0yD2oLKI43XY33GVxmnvLntbLPiXxg5A2PFd0ap/9HZCxej+uOV9pgZGqzoTZmwXv1sIBS1Ziymkbb7hF/tozs9BfNM9nAMvw9Oc4oVOmSb1Z5t4q1X5gDH9Tz2T+B/poh93BiR18OtXHBgE5+7V+H+7zTCYKr6ztS3S4pcnKOtTWmIs0PaLUpN+V7UnyJpaWSAbk2U/xg7q7dqXVADF7rTwoqe0w7z9YAqvDrCPDg2XohFT2jznRvWfJe30YQOxHdBQ+qLGcXynJJDjx2S0H37zaWNuncjaxXX3s19SDxYXKm1tcbKNTmti9AmVD0FPrl6wURtcX8npg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
